import streamlit as st
import anthropic
import base64
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io
import time

# Page config
st.set_page_config(
    page_title="PDF to Word Converter",
    page_icon="📄",
    layout="wide"
)

# Initialize Anthropic client
@st.cache_resource
def get_anthropic_client():
    api_key = st.secrets.get("ANTHROPIC_API_KEY", None)
    if not api_key:
        st.error("Please set ANTHROPIC_API_KEY in Streamlit secrets")
        st.stop()
    return anthropic.Anthropic(api_key=api_key)

def pdf_to_base64(pdf_file):
    """Convert uploaded PDF to base64"""
    return base64.standard_b64encode(pdf_file.read()).decode("utf-8")

def analyze_pdf_with_claude(pdf_base64):
    """Send PDF to Claude for analysis"""
    client = get_anthropic_client()
    
    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=4000,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "document",
                        "source": {
                            "type": "base64",
                            "media_type": "application/pdf",
                            "data": pdf_base64,
                        },
                    },
                    {
                        "type": "text",
                        "text": """Please analyze this document and provide TWO separate outputs:

1. SUMMARY: A concise summary of the document (2-3 paragraphs)
2. KEY_POINTS: A detailed list of key points, findings, and important information

Format your response EXACTLY as:
===SUMMARY===
[Your summary here]

===KEY_POINTS===
[Your key points here]"""
                    }
                ],
            }
        ],
    )
    
    return message.content[0].text

def create_word_document(title, content):
    """Create a Word document with the given content"""
    doc = Document()
    
    # Add title
    title_paragraph = doc.add_heading(title, level=1)
    title_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add content
    doc.add_paragraph(content)
    
    # Save to bytes
    doc_io = io.BytesIO()
    doc.save(doc_io)
    doc_io.seek(0)
    
    return doc_io

def parse_ai_response(response_text):
    """Parse the AI response into summary and key points"""
    parts = response_text.split("===SUMMARY===")
    if len(parts) < 2:
        return response_text[:len(response_text)//2], response_text[len(response_text)//2:]
    
    summary_and_rest = parts[1].split("===KEY_POINTS===")
    summary = summary_and_rest[0].strip()
    key_points = summary_and_rest[1].strip() if len(summary_and_rest) > 1 else ""
    
    return summary, key_points

# Main app
st.title("📄 PDF to Word Document Converter")
st.write("Upload a PDF and get 2 Word documents generated by AI")

# File uploader
uploaded_file = st.file_uploader("Choose a PDF file", type=['pdf'])

if uploaded_file is not None:
    st.success(f"File uploaded: {uploaded_file.name}")
    
    # Process button
    if st.button("🚀 Process Document", type="primary"):
        
        # Progress bar and status
        progress_bar = st.progress(0)
        status_text = st.empty()
        
        try:
            # Step 1: Convert PDF to base64
            status_text.text("📤 Uploading PDF...")
            progress_bar.progress(20)
            pdf_base64 = pdf_to_base64(uploaded_file)
            
            # Step 2: Analyze with Claude
            status_text.text("🤖 AI is analyzing the document...")
            progress_bar.progress(40)
            ai_response = analyze_pdf_with_claude(pdf_base64)
            
            # Step 3: Parse response
            status_text.text("📝 Generating Word documents...")
            progress_bar.progress(70)
            summary, key_points = parse_ai_response(ai_response)
            
            # Step 4: Create Word documents
            doc1 = create_word_document("Document Summary", summary)
            doc2 = create_word_document("Key Points & Findings", key_points)
            
            progress_bar.progress(100)
            status_text.text("✅ Processing complete!")
            
            # Display results
            st.success("Documents generated successfully!")
            
            col1, col2 = st.columns(2)
            
            with col1:
                st.subheader("📋 Document 1: Summary")
                st.download_button(
                    label="⬇️ Download Summary",
                    data=doc1,
                    file_name=f"{uploaded_file.name.replace('.pdf', '')}_summary.docx",
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                )
                with st.expander("Preview Summary"):
                    st.write(summary)
            
            with col2:
                st.subheader("📊 Document 2: Key Points")
                st.download_button(
                    label="⬇️ Download Key Points",
                    data=doc2,
                    file_name=f"{uploaded_file.name.replace('.pdf', '')}_keypoints.docx",
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                )
                with st.expander("Preview Key Points"):
                    st.write(key_points)
            
        except Exception as e:
            st.error(f"An error occurred: {str(e)}")
            progress_bar.empty()
            status_text.empty()

else:
    st.info("👆 Please upload a PDF file to get started")

# Footer
st.markdown("---")
st.markdown("*Powered by Claude AI & Streamlit*")
